version: "3.9"

services:
  frontend:
    build:
      context: ../applications/frontend
      dockerfile: Dockerfile
    container_name: cloudmart-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend



  backend:
    build:
      context: ../applications/backend
      dockerfile: Dockerfile
    container_name: cloudmart-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://cloudmart:cloudmartpass@db:5432/cloudmart
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  db:
    image: postgres:15
    container_name: cloudmart-db
    restart: always
    environment:
      POSTGRES_USER: cloudmart
      POSTGRES_PASSWORD: cloudmartpass
      POSTGRES_DB: cloudmart
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudmart -d cloudmart"]
      interval: 5s
      timeout: 5s
      retries: 5



  redis:
    image: redis:7
    container_name: cloudmart-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
